[package]
name = "tl_yargl"
version = "0.7.7"
authors = ["y21"]
edition = "2021"
license = "MIT"
description = "Fast HTML and CSS parser written in pure Rust"
repository = "https://github.com/dz1230/tl_yargl"
homepage = "https://github.com/dz1230/tl_yargl"
readme = "README.md"
documentation = "https://docs.rs/tl_yargl"
keywords = ["html", "parser"]
categories = ["parser-implementations", "parsing"]
exclude = [".github/*"]

[features]
simd = []

# for fuzzing and benchmarking internals, we need to make them public so that they can be accessed from outside testing crates
# users of the library should never use these directly
__INTERNALS_DO_NOT_USE = []

[dependencies]


[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "tl_yargl"
harness = false
